---
- name: Instalar MariaDB
  hosts: ubuntu01
  become: true
  vars_files:
    - ../vars/database.yaml

  tasks:

    - name: Instalar MariaDB
      ansible.builtin.apt:
        name: mariadb-server
        state: present

    - name: Instalar dependencias para Ansible MariaDB
      ansible.builtin.apt:
        name: python3-pymysql
        state: present
        
    - name: Asociar MariaDB a cualquier interfaz
      ansible.builtin.lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
      notify: Reiniciar mariadb server

    - name: Iniciar MariaDB
      ansible.builtin.systemd_service:
        name: mariadb
        state: started
        enabled: true

    - name: Crear base de datos
      community.mysql.mysql_db:
        name: "{{ DB_DBASE }}"
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Crear tabla de cumpleaños
      community.mysql.mysql_query:
        login_db: "{{ DB_DBASE }}"
        login_unix_socket: /run/mysqld/mysqld.sock
        query: |
          CREATE TABLE IF NOT EXISTS cumpleaños (
          id INT AUTO_INCREMENT PRIMARY KEY,
          nombre VARCHAR(100) NOT NULL,
          fecha DATE NOT NULL
          );

    - name: Insertar datos iniciales
      community.mysql.mysql_query:
        login_db: "{{ DB_DBASE }}"
        login_unix_socket: /run/mysqld/mysqld.sock
        query:
          - |
            INSERT INTO cumpleaños (nombre, fecha)
            SELECT 'Frodo Baggins', '2005-01-14'
            WHERE NOT EXISTS (
              SELECT 1
              FROM cumpleaños
              WHERE nombre = 'Frodo Baggins'
                AND fecha = '2005-01-14'
            );
          - |
            INSERT INTO cumpleaños (nombre, fecha)
            SELECT 'Aragorn', '2004-02-09'
            WHERE NOT EXISTS (
              SELECT 1
              FROM cumpleaños
              WHERE nombre = 'Aragorn'
                AND fecha = '2004-02-09'
            );
          - |
            INSERT INTO cumpleaños (nombre, fecha)
            SELECT 'Arwen Undomiel', '1994-12-09'
            WHERE NOT EXISTS (
              SELECT 1
              FROM cumpleaños
              WHERE nombre = 'Arwen Undomiel'
                AND fecha = '1994-12-09'
            );

    - name: Crear usuario de la app
      community.mysql.mysql_user:
        name: "{{ DB_USER }}"
        host: "10.0.2.15"
        password: "{{ DB_PASS }}"
        priv: "{{ DB_DBASE }}.*:SELECT,INSERT,UPDATE,DELETE"
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Checkear si la contrasena de root existe
      ansible.mysql.mysql_user:
        login_user: root
        login_password: ""
        login_unix_socket: /var/run/mysqld/mysqld.sock
        check_implicit_admin: true
        name: root
        host: localhost
      register: mysql_root_check
      ignore_error: true

    - name: Debug password status
      ansible.builtin.debug:
        msg: mysql_root_check
      when: mysql_root_check.failed is false

    - name: Iniciar contrasena de root si no esta configurada
      include_tasks: ../tasks/initialize_root.yaml
      when: mysql_root_check.failed is false

    - name: Permitir connecciones a la BD en UFW
      community.general.ufw:
        port: 3306
        proto: tcp
        rule: allow
        from_ip: 10.0.2.15

  handlers:

    - name: Reiniciar mariadb server
      ansible.builtin.systemd_service:
        name: mariadb
        state: restarted
